### PR TITLE
fix json unmarshal bug and add support for container NetworkMode

### PR DESCRIPTION
**Pull request by WIZARD-CXY**
1 There exists a small bug in the json unmarshal code part. The reqParams.ClientRequest.Body should actually unmarshal to a dockerclient.ContainerConfig.HostConfig struct.
2 When user use docker container with container network mode, I think they don't want socketplane to change it. It happens in kubernetes ,when real user container is using infra container's net namespace.

Test done!

### CODE REVIEW

**Comment by WIZARD-CXY** [comment]
any comment ,guys?

**Comment by mavenugo** [comment]
@WIZARD-CXY sorry about the delay. 
Paging our powerstrip expert @mrjana to take a look.

**Comment by mrjana** [comment]
@WIZARD-CXY The ClientRequest.Body contains the whole body from the original client request. So I am not sure why you think we should unmarshall that into jsonBody.HostConfig.

Also I don't see a point in using socketplane if you are going to use kubernetes for networking so again I am not seeing this use case where you want this change

**Comment by WIZARD-CXY** [comment]
1 I actually thought ClientRequest.Body contains the whole body from the original client request.But after some failure and debug.I found it actually not. Below is a sample ClientRequest.Body I grabbed from sockerplane adapter
```
{PowerstripProtocolVersion:1 Type:pre-hook ClientRequest:{Method:POST Request:/containers/b34e299c61d07e3082d0aff64b87bd0587810b23d757e5605f38313d746ed171/start Body:{"Binds":["/var/lib/kubelet/pods/a6bf3cbb-d486-11e4-bf0c-f8bc12984e72/containers/master/b34e299c61d07e3082d0aff64b87bd0587810b23d757e5605f38313d746ed171:/dev/termination-log"],"NetworkMode":"container:06adc6d4be0ee7da17af60a428f4e4c770ac2583f0af6024d769456c0a9b68df","IpcMode":"container:06adc6d4be0ee7da17af60a428f4e4c770ac2583f0af6024d769456c0a9b68df","RestartPolicy":{}}} ServerResponse:{Body: Code:0 ContentType:}}
```
It matches the dockerclient.ContainerConfig.HostConfig struct, not  dockerclient.ContainerConfig. I am using fsouza/go-dockerclient.

2 What I want to say is it would be better to set a specific option, like `--net=sp` when use docker run to indicate this container will use socketplane to set the network settings, Now it configures all the container net settings to socketplane settings no matter user wants to run host ,container or none networkmode when using socketplane adapter.It maybe less flexible, what do you think?@mrjana And I used the socketplane to provide advanced network connectoin and isolation for pods in k8s than flannel.

**Comment by mavenugo** [comment]
I will let @mrjana answer to #1 above.
>> 2 What I want to say is it would be better to set a specific option, like --net=sp when use docker run to indicate this container will use socketplane to set the network settings, Now it configures all the container net settings to socketplane settings no matter user wants to run host ,container or none networkmode when using socketplane adapter.It maybe less flexible, what do you think?
@WIZARD-CXY we are working with the Docker community to define this exact requirement in a more generic fashion with the concept of Docker plugins. And providing generic docker network extension APIs (https://github.com/docker/docker/issues/9983) which every networking solution for Docker can make use of. This will avoid the need for a solution specific configuration such as --net=sp. You will start to see this happening shortly in native Docker platform. Hope that makes sense.

>> @mrjana And I used the socketplane to provide advanced network connectoin and isolation for pods in k8s than flannel.
Thanks. I think it is a good idea. Please point us to any repository that you are working on and we will be happy to help in any form.

**Comment by WIZARD-CXY** [comment]
Thanks @mavenugo first
I was the contributor of kubernetes on deploying the kubernetes on ubuntu cluster, now we use flannel as the network solution.See https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/getting-started-guides/ubuntu_multinodes_cluster.md, but it is too simple for our lab usage, we want to have be more SDN.So we want to integrate socketplane into k8s. The work is done.
But we found there seems another way to add support to kubernetes network functionality.The redhat guys are working on k8s network plugins,So our solution maybe deprecated.

**Comment by WIZARD-CXY** [comment]
@mrjana I found that when using docker cli command to the socketplane adapter,  the ClientRequest.Body contains the whole body from the original client request just as below:
```
Body:{"Hostname":"","Domainname":"","User":"","Memory":0,"MemorySwap":0,"CpuShares":0,"Cpuset":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"PortSpecs":null,"ExposedPorts":{},"Tty":true,"OpenStdin":true,"StdinOnce":false,"Env":[],"Cmd":null,"Image":"10.10.103.215:5000/sshd","Volumes":{},"WorkingDir":"","Entrypoint":null,"NetworkDisabled":false,"MacAddress":"","OnBuild":null,"HostConfig":{"Binds":null,"ContainerIDFile":"","LxcConf":[],"Privileged":false,"PortBindings":{},"Links":null,"PublishAllPorts":false,"Dns":null,"DnsSearch":null,"ExtraHosts":null,"VolumesFrom":null,"Devices":[],"NetworkMode":"bridge","IpcMode":"","PidMode":"","CapAdd":null,"CapDrop":null,"RestartPolicy":{"Name":"","MaximumRetryCount":0},"SecurityOpt":null,"ReadonlyRootfs":false}}
```
So the previous code is running correctly, but for the fsouza/go-dockerclient it is wrong, I will debug and see where the differences are.

**Comment by WIZARD-CXY** [comment]
Close the pull request since there are no significant changes

**Pull request closed without merging**
